'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FurryArtStudio.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Ok 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property About_BtnOK() As String
            Get
                Return ResourceManager.GetString("About_BtnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 GitHub 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property About_LinkGitHub() As String
            Get
                Return ResourceManager.GetString("About_LinkGitHub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 License 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property About_LinkLicense() As String
            Get
                Return ResourceManager.GetString("About_LinkLicense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Privacy Policy 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property About_LinkPrivacy() As String
            Get
                Return ResourceManager.GetString("About_LinkPrivacy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User Terms 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property About_LinkUserAgreement() As String
            Get
                Return ResourceManager.GetString("About_LinkUserAgreement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Website 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property About_LinkWebSite() As String
            Get
                Return ResourceManager.GetString("About_LinkWebSite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 About 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property About_Title() As String
            Get
                Return ResourceManager.GetString("About_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Extract result 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ColorDialog_Title() As String
            Get
                Return ResourceManager.GetString("ColorDialog_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Select the image(s) to add 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_AddImg() As String
            Get
                Return ResourceManager.GetString("Edit_AddImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Add... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_BtnAddItem() As String
            Get
                Return ResourceManager.GetString("Edit_BtnAddItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Cancel 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_BtnCancel() As String
            Get
                Return ResourceManager.GetString("Edit_BtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Delete... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_BtnDel() As String
            Get
                Return ResourceManager.GetString("Edit_BtnDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;OK 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_BtnOK() As String
            Get
                Return ResourceManager.GetString("Edit_BtnOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Save 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_BtnSave() As String
            Get
                Return ResourceManager.GetString("Edit_BtnSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Set as &amp;Preview 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_BtnSetPreview() As String
            Get
                Return ResourceManager.GetString("Edit_BtnSetPreview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error creating folder: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_CreateFailed() As String
            Get
                Return ResourceManager.GetString("Edit_CreateFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Are you sure you want to delete the file &apos;{0}&apos;? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_DelConfirm() As String
            Get
                Return ResourceManager.GetString("Edit_DelConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Deletion failed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_DelFailed() As String
            Get
                Return ResourceManager.GetString("Edit_DelFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Edit Manuscript 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_EditTitle() As String
            Get
                Return ResourceManager.GetString("Edit_EditTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Image files(*.jpg;*.jpeg;*.png;*.bmp;*.gif)|*.jpg;*.jpeg;*.png;*.bmp;*.gif|All files(*.*)|*.* 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_ImageFilter() As String
            Get
                Return ResourceManager.GetString("Edit_ImageFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Author: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_LblAuthor() As String
            Get
                Return ResourceManager.GetString("Edit_LblAuthor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Roles: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_LblCharacters() As String
            Get
                Return ResourceManager.GetString("Edit_LblCharacters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Create At: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_LblCreate() As String
            Get
                Return ResourceManager.GetString("Edit_LblCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Import At: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_LblImport() As String
            Get
                Return ResourceManager.GetString("Edit_LblImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Notes: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_LblNotes() As String
            Get
                Return ResourceManager.GetString("Edit_LblNotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tags: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_LblTags() As String
            Get
                Return ResourceManager.GetString("Edit_LblTags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Title: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_LblTitle() As String
            Get
                Return ResourceManager.GetString("Edit_LblTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Update At: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_LblUpdate() As String
            Get
                Return ResourceManager.GetString("Edit_LblUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The file has been marked for deletion 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_MarkDel() As String
            Get
                Return ResourceManager.GetString("Edit_MarkDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 New Manuscript 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_NewTitle() As String
            Get
                Return ResourceManager.GetString("Edit_NewTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No Author 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_NoAuthor() As String
            Get
                Return ResourceManager.GetString("Edit_NoAuthor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No Title 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_NoTitle() As String
            Get
                Return ResourceManager.GetString("Edit_NoTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please select the file to delete first 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_SelectDel() As String
            Get
                Return ResourceManager.GetString("Edit_SelectDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Invalid create time format! Please use the format yyyy-MM-dd HH:mm:ss. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_TimeInvalid() As String
            Get
                Return ResourceManager.GetString("Edit_TimeInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The create time cannot be later than the current time. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Edit_TimeOverflow() As String
            Get
                Return ResourceManager.GetString("Edit_TimeOverflow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Scientifically and efficiently organize and manage Fursona sketches, reference materials, original OC content, and image documents 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property FAS_Description() As String
            Get
                Return ResourceManager.GetString("FAS_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 FurryArtStudio 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property FurryArtStudio() As String
            Get
                Return ResourceManager.GetString("FurryArtStudio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Hitokoto 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Hitokoto() As String
            Get
                Return ResourceManager.GetString("Hitokoto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Created at: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Hitokoto_Createdat() As String
            Get
                Return ResourceManager.GetString("Hitokoto_Createdat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Creator: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Hitokoto_Creator() As String
            Get
                Return ResourceManager.GetString("Hitokoto_Creator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;More info 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Hitokoto_MoreInfo() As String
            Get
                Return ResourceManager.GetString("Hitokoto_MoreInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Reviewer: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Hitokoto_Reviewer() As String
            Get
                Return ResourceManager.GetString("Hitokoto_Reviewer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Type: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Hitokoto_Type() As String
            Get
                Return ResourceManager.GetString("Hitokoto_Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Clone Manuscript Library 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Input_CloneLibTitle() As String
            Get
                Return ResourceManager.GetString("Input_CloneLibTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 New Manuscript Library 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Input_NewLibTitle() As String
            Get
                Return ResourceManager.GetString("Input_NewLibTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Rename Manuscript Library 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Input_RenameLibTitle() As String
            Get
                Return ResourceManager.GetString("Input_RenameLibTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Copy of {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Input_TxtClone() As String
            Get
                Return ResourceManager.GetString("Input_TxtClone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 New Manuscript Library 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Input_TxtNewLib() As String
            Get
                Return ResourceManager.GetString("Input_TxtNewLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 CSV files (*.csv)|*.csv|All files (*.*)|*.* 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_FileFilterCSV() As String
            Get
                Return ResourceManager.GetString("Main_FileFilterCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 PAW files(*.paw)|*.paw|ZIP files(*.zip)|*.zip 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_FileFilterPAW() As String
            Get
                Return ResourceManager.GetString("Main_FileFilterPAW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Characters: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblCharacter() As String
            Get
                Return ResourceManager.GetString("Main_LblCharacter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} differences 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblDifference() As String
            Get
                Return ResourceManager.GetString("Main_LblDifference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Library: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblLibName() As String
            Get
                Return ResourceManager.GetString("Main_LblLibName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} manuscript(s) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblMs() As String
            Get
                Return ResourceManager.GetString("Main_LblMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;No Manuscript Library&gt; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblNoLib() As String
            Get
                Return ResourceManager.GetString("Main_LblNoLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 0 manuscript 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblNoMs() As String
            Get
                Return ResourceManager.GetString("Main_LblNoMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Page: 0/0 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblNoPage() As String
            Get
                Return ResourceManager.GetString("Main_LblNoPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please select an item 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblNoSelect() As String
            Get
                Return ResourceManager.GetString("Main_LblNoSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Storage: 0B (0 file) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblNoStorage() As String
            Get
                Return ResourceManager.GetString("Main_LblNoStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Notes: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblNotes() As String
            Get
                Return ResourceManager.GetString("Main_LblNotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Page: {0}/{1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblPage() As String
            Get
                Return ResourceManager.GetString("Main_LblPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Page: 1/{0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblPage1() As String
            Get
                Return ResourceManager.GetString("Main_LblPage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Searched {0} manuscript(s) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblSearchedMs() As String
            Get
                Return ResourceManager.GetString("Main_LblSearchedMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Selected: {0}/{1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblSelectMs() As String
            Get
                Return ResourceManager.GetString("Main_LblSelectMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Selected: 1/{0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblSelectMs1() As String
            Get
                Return ResourceManager.GetString("Main_LblSelectMs1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Storage: {0} ({1:N0} file(s)) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblStorage() As String
            Get
                Return ResourceManager.GetString("Main_LblStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tags: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblTags() As String
            Get
                Return ResourceManager.GetString("Main_LblTags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {0} item(s) selected 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_LblTitleSelect() As String
            Get
                Return ResourceManager.GetString("Main_LblTitleSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Apache License 2.0 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrLicense() As String
            Get
                Return ResourceManager.GetString("Main_StrLicense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Operation cancelled by user 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrOperationCancelled() As String
            Get
                Return ResourceManager.GetString("Main_StrOperationCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Privacy Policy 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrPrivacy() As String
            Get
                Return ResourceManager.GetString("Main_StrPrivacy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Library: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrPropLib() As String
            Get
                Return ResourceManager.GetString("Main_StrPropLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Library path: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrPropLibPath() As String
            Get
                Return ResourceManager.GetString("Main_StrPropLibPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Manuscripts: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrPropMsCount() As String
            Get
                Return ResourceManager.GetString("Main_StrPropMsCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Current time: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrPropNowTime() As String
            Get
                Return ResourceManager.GetString("Main_StrPropNowTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Storage: {0} File(s): {1:N0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrPropStorage() As String
            Get
                Return ResourceManager.GetString("Main_StrPropStorage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User Terms 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrTerms() As String
            Get
                Return ResourceManager.GetString("Main_StrTerms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 What&apos;s New 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Main_StrWhatsNew() As String
            Get
                Return ResourceManager.GetString("Main_StrWhatsNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;About... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_About() As String
            Get
                Return ResourceManager.GetString("Mnu_About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Advanced Search... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_AdvancedSearch() As String
            Get
                Return ResourceManager.GetString("Mnu_AdvancedSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Always on &amp;Top 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_AlwaysOnTop() As String
            Get
                Return ResourceManager.GetString("Mnu_AlwaysOnTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Bug Report 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_BugReport() As String
            Get
                Return ResourceManager.GetString("Mnu_BugReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Check for &amp;Updates 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_CheckUpdate() As String
            Get
                Return ResourceManager.GetString("Mnu_CheckUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 C&amp;lone... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Clone() As String
            Get
                Return ResourceManager.GetString("Mnu_Clone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Close 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Close() As String
            Get
                Return ResourceManager.GetString("Mnu_Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Copy Folder 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Copy() As String
            Get
                Return ResourceManager.GetString("Mnu_Copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Copy Folder Pa&amp;th 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_CopyPath() As String
            Get
                Return ResourceManager.GetString("Mnu_CopyPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Create Desktop &amp;Shortcut 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_CreateShortcut() As String
            Get
                Return ResourceManager.GetString("Mnu_CreateShortcut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 C&amp;urrent Library 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_CurrentLib() As String
            Get
                Return ResourceManager.GetString("Mnu_CurrentLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Delete... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Delete() As String
            Get
                Return ResourceManager.GetString("Mnu_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Developer Tools... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_DevTools() As String
            Get
                Return ResourceManager.GetString("Mnu_DevTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Donate 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Donate() As String
            Get
                Return ResourceManager.GetString("Mnu_Donate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Edit... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Edit() As String
            Get
                Return ResourceManager.GetString("Mnu_Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Elevated 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Elevated() As String
            Get
                Return ResourceManager.GetString("Mnu_Elevated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 E&amp;xit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Exit() As String
            Get
                Return ResourceManager.GetString("Mnu_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Export... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Export() As String
            Get
                Return ResourceManager.GetString("Mnu_Export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Export as CS&amp;V... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_ExportCSV() As String
            Get
                Return ResourceManager.GetString("Mnu_ExportCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 E&amp;xport... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_ExportMs() As String
            Get
                Return ResourceManager.GetString("Mnu_ExportMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Feedback 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Feedback() As String
            Get
                Return ResourceManager.GetString("Mnu_Feedback", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;File 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_File() As String
            Get
                Return ResourceManager.GetString("Mnu_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Statistics... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_FormProperties() As String
            Get
                Return ResourceManager.GetString("Mnu_FormProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;GitHub 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_GitHub() As String
            Get
                Return ResourceManager.GetString("Mnu_GitHub", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Help 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Help() As String
            Get
                Return ResourceManager.GetString("Mnu_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Import... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Import() As String
            Get
                Return ResourceManager.GetString("Mnu_Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Library 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Lib() As String
            Get
                Return ResourceManager.GetString("Mnu_Lib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;License... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_License() As String
            Get
                Return ResourceManager.GetString("Mnu_License", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Load Sponsor List 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_LoadSponsors() As String
            Get
                Return ResourceManager.GetString("Mnu_LoadSponsors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Manuscript 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Ms() As String
            Get
                Return ResourceManager.GetString("Mnu_Ms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;My Feedback 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_MyFeedback() As String
            Get
                Return ResourceManager.GetString("Mnu_MyFeedback", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;New... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_New() As String
            Get
                Return ResourceManager.GetString("Mnu_New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;New Manuscript... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_NewMs() As String
            Get
                Return ResourceManager.GetString("Mnu_NewMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Next Page 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Next() As String
            Get
                Return ResourceManager.GetString("Mnu_Next", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Open &amp;Afdian Official Website 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_OpenAfdian() As String
            Get
                Return ResourceManager.GetString("Mnu_OpenAfdian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Open &amp;Program Folder 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_OpenFolder() As String
            Get
                Return ResourceManager.GetString("Mnu_OpenFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Open Folder 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_OpenPath() As String
            Get
                Return ResourceManager.GetString("Mnu_OpenPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Open &amp;Terminal Here 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_OpenTerminal() As String
            Get
                Return ResourceManager.GetString("Mnu_OpenTerminal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Options... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Options() As String
            Get
                Return ResourceManager.GetString("Mnu_Options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Play 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Play() As String
            Get
                Return ResourceManager.GetString("Mnu_Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Pr&amp;evious Page 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Prev() As String
            Get
                Return ResourceManager.GetString("Mnu_Prev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Print... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Print() As String
            Get
                Return ResourceManager.GetString("Mnu_Print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Privacy Policy... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Privacy() As String
            Get
                Return ResourceManager.GetString("Mnu_Privacy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Pr&amp;ivacy Protect 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_PrivacyProtect() As String
            Get
                Return ResourceManager.GetString("Mnu_PrivacyProtect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Statistics... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Properties() As String
            Get
                Return ResourceManager.GetString("Mnu_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Refresh 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Refresh() As String
            Get
                Return ResourceManager.GetString("Mnu_Refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Rena&amp;me... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Rename() As String
            Get
                Return ResourceManager.GetString("Mnu_Rename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Restart as Administrator 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_RunAsElevated() As String
            Get
                Return ResourceManager.GetString("Mnu_RunAsElevated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Find 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Search() As String
            Get
                Return ResourceManager.GetString("Mnu_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Select &amp;All 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_SelectAll() As String
            Get
                Return ResourceManager.GetString("Mnu_SelectAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Reverse Select 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_SelectReverse() As String
            Get
                Return ResourceManager.GetString("Mnu_SelectReverse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Suggest Feature 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Suggestions() As String
            Get
                Return ResourceManager.GetString("Mnu_Suggestions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User &amp;Terms... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Terms() As String
            Get
                Return ResourceManager.GetString("Mnu_Terms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Tutorial 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Tutorial() As String
            Get
                Return ResourceManager.GetString("Mnu_Tutorial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Pre&amp;view 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_View() As String
            Get
                Return ResourceManager.GetString("Mnu_View", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;View 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Views() As String
            Get
                Return ResourceManager.GetString("Mnu_Views", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Website 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_Website() As String
            Get
                Return ResourceManager.GetString("Mnu_Website", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;What&apos;s New 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Mnu_WhatsNew() As String
            Get
                Return ResourceManager.GetString("Mnu_WhatsNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 This action is irreversible! 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_CannotBeIrreversible() As String
            Get
                Return ResourceManager.GetString("Msg_CannotBeIrreversible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Retrieving sponsor information... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_CheckingSponsor() As String
            Get
                Return ResourceManager.GetString("Msg_CheckingSponsor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Checking for update... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_CheckingUpdate() As String
            Get
                Return ResourceManager.GetString("Msg_CheckingUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to check for update 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_CheckUpdateFailed() As String
            Get
                Return ResourceManager.GetString("Msg_CheckUpdateFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Copy details 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_CopyDetails() As String
            Get
                Return ResourceManager.GetString("Msg_CopyDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to export CSV file 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_CreateCSVFailed() As String
            Get
                Return ResourceManager.GetString("Msg_CreateCSVFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Creation failed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_CreateFailed() As String
            Get
                Return ResourceManager.GetString("Msg_CreateFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to create desktop shortcut 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_CreateShortcutFailed() As String
            Get
                Return ResourceManager.GetString("Msg_CreateShortcutFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Do you want to move the manuscript library {0} to the Recycle Bin? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_DeleteLib() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 move to the Recycle Bin 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_DeleteLibConfirm() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteLibConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Do you want to permanently delete the manuscript library {0}?  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_DeleteLibPermanently() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteLibPermanently", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Are you sure you want to move these {0} item(s) to the Recycle Bin? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_DeleteMs() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Delete manuscript(s) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_DeleteMsConfirm() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMsConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ...and {0} other items 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_DeleteMsCount() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMsCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Are you sure you want to permanently delete {0} manuscript(s)? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_DeleteMsPermanently() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMsPermanently", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permanently delete manuscript(s) 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_DeleteMsPermanentlyConfirm() As String
            Get
                Return ResourceManager.GetString("Msg_DeleteMsPermanentlyConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Download new version 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_DownloadNewVer() As String
            Get
                Return ResourceManager.GetString("Msg_DownloadNewVer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Elevation failed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_ElevatedFailed() As String
            Get
                Return ResourceManager.GetString("Msg_ElevatedFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Export complete 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_ExportComplete() As String
            Get
                Return ResourceManager.GetString("Msg_ExportComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Export failed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_ExportFailed() As String
            Get
                Return ResourceManager.GetString("Msg_ExportFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 I know what I&apos;m doing! 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_IKnowWhatIamDoing() As String
            Get
                Return ResourceManager.GetString("Msg_IKnowWhatIamDoing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to load image 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_ImageLoadFailed() As String
            Get
                Return ResourceManager.GetString("Msg_ImageLoadFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to delete library 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_LibDeleteFailed() As String
            Get
                Return ResourceManager.GetString("Msg_LibDeleteFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 You are about to open {0} folders at once. Do you want to continue? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_MultiFolderOpen() As String
            Get
                Return ResourceManager.GetString("Msg_MultiFolderOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 New version found: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_NewVerFound() As String
            Get
                Return ResourceManager.GetString("Msg_NewVerFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The current manuscript has no image files 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_NoImg() As String
            Get
                Return ResourceManager.GetString("Msg_NoImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No printable image files found 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_NoPrintFile() As String
            Get
                Return ResourceManager.GetString("Msg_NoPrintFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;No sponsor information&gt; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_NoSponsor() As String
            Get
                Return ResourceManager.GetString("Msg_NoSponsor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error while printing 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_PrintFailed() As String
            Get
                Return ResourceManager.GetString("Msg_PrintFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - Characters: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsCharacters() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsCharacters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - Creation time: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsCreate() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - Import time: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsImport() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ## Manuscript information: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsInfo() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - Notes: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsNotes() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsNotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Current time: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsNow() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsNow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 *Powered by FurryArtStudio* 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsSupportByFAS() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsSupportByFAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - Tags: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsTags() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsTags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ### Title: {0} - {1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsTitle() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Total {0} manuscripts 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsTotal() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - Update time: {0:yyyy-MM-dd HH:mm:ss} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsUpdate() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  - UUID: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_StrMsUUID() As String
            Get
                Return ResourceManager.GetString("Msg_StrMsUUID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to start terminal 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_TerminalFailed() As String
            Get
                Return ResourceManager.GetString("Msg_TerminalFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Your version is up to date 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Msg_UptoDate() As String
            Get
                Return ResourceManager.GetString("Msg_UptoDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Cancel 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_BtnCancel() As String
            Get
                Return ResourceManager.GetString("Print_BtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Print 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_BtnPrint() As String
            Get
                Return ResourceManager.GetString("Print_BtnPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Landscape 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_Horizontal() As String
            Get
                Return ResourceManager.GetString("Print_Horizontal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Bottom: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_LblBottom() As String
            Get
                Return ResourceManager.GetString("Print_LblBottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Copies: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_LblCount() As String
            Get
                Return ResourceManager.GetString("Print_LblCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Left: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_LblLeft() As String
            Get
                Return ResourceManager.GetString("Print_LblLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Paper: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_LblPaper() As String
            Get
                Return ResourceManager.GetString("Print_LblPaper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Printer: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_LblPrinter() As String
            Get
                Return ResourceManager.GetString("Print_LblPrinter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Right: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_LblRight() As String
            Get
                Return ResourceManager.GetString("Print_LblRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Top: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_LblTop() As String
            Get
                Return ResourceManager.GetString("Print_LblTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Layout: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_LblType() As String
            Get
                Return ResourceManager.GetString("Print_LblType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Printer &amp;Manager 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_PrinterManager() As String
            Get
                Return ResourceManager.GetString("Print_PrinterManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Print 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_Title() As String
            Get
                Return ResourceManager.GetString("Print_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Portrait 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Print_Vertical() As String
            Get
                Return ResourceManager.GetString("Print_Vertical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Close 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Prop_BtnClose() As String
            Get
                Return ResourceManager.GetString("Prop_BtnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cloning manuscript library... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Cloning() As String
            Get
                Return ResourceManager.GetString("Stat_Cloning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Closing manuscript library... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Closing() As String
            Get
                Return ResourceManager.GetString("Stat_Closing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Creating manuscript library... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_CreatingLib() As String
            Get
                Return ResourceManager.GetString("Stat_CreatingLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Deleting manuscript library... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_DeletingLib() As String
            Get
                Return ResourceManager.GetString("Stat_DeletingLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Deleting manuscript... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_DeletingMs() As String
            Get
                Return ResourceManager.GetString("Stat_DeletingMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Editing manuscript... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_EditMs() As String
            Get
                Return ResourceManager.GetString("Stat_EditMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Exporting to CSV... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_ExportCSV() As String
            Get
                Return ResourceManager.GetString("Stat_ExportCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Exporting... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Exporting() As String
            Get
                Return ResourceManager.GetString("Stat_Exporting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Importing... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Importing() As String
            Get
                Return ResourceManager.GetString("Stat_Importing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Initializing... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Init() As String
            Get
                Return ResourceManager.GetString("Stat_Init", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Loading data... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Loading() As String
            Get
                Return ResourceManager.GetString("Stat_Loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Creating new manuscript... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_NewMs() As String
            Get
                Return ResourceManager.GetString("Stat_NewMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Setting preferences... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_OpenProp() As String
            Get
                Return ResourceManager.GetString("Stat_OpenProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Initializing print... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_PreparePrint() As String
            Get
                Return ResourceManager.GetString("Stat_PreparePrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Printing... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Printing() As String
            Get
                Return ResourceManager.GetString("Stat_Printing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Ready 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Ready() As String
            Get
                Return ResourceManager.GetString("Stat_Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Renaming manuscript library... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Renaming() As String
            Get
                Return ResourceManager.GetString("Stat_Renaming", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Searching... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_Searching() As String
            Get
                Return ResourceManager.GetString("Stat_Searching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Showing hitokoto... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Stat_ShowHitokoto() As String
            Get
                Return ResourceManager.GetString("Stat_ShowHitokoto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Artwork Information 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_ArtInfo() As String
            Get
                Return ResourceManager.GetString("View_ArtInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Author: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Author() As String
            Get
                Return ResourceManager.GetString("View_Author", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Copy 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Copy() As String
            Get
                Return ResourceManager.GetString("View_Copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Copy Path 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_CopyPath() As String
            Get
                Return ResourceManager.GetString("View_CopyPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Creation Time: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Create() As String
            Get
                Return ResourceManager.GetString("View_Create", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Dark Mode 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Dark() As String
            Get
                Return ResourceManager.GetString("View_Dark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Bit Depth: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Depth() As String
            Get
                Return ResourceManager.GetString("View_Depth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Extract 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Extract() As String
            Get
                Return ResourceManager.GetString("View_Extract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unable to open properties window 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_FailedtoOpenProp() As String
            Get
                Return ResourceManager.GetString("View_FailedtoOpenProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 File Creation Time: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_FileCreateTime() As String
            Get
                Return ResourceManager.GetString("View_FileCreateTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 File Modification Time: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_FileModifyTime() As String
            Get
                Return ResourceManager.GetString("View_FileModifyTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 File Path: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_FilePath() As String
            Get
                Return ResourceManager.GetString("View_FilePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 File P&amp;roperties 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_FileProperties() As String
            Get
                Return ResourceManager.GetString("View_FileProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 File Size: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_FileSize() As String
            Get
                Return ResourceManager.GetString("View_FileSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 File Type: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_FileType() As String
            Get
                Return ResourceManager.GetString("View_FileType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Full Screen 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Fullscreen() As String
            Get
                Return ResourceManager.GetString("View_Fullscreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Help... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Help() As String
            Get
                Return ResourceManager.GetString("View_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Close        Esc 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpClose() As String
            Get
                Return ResourceManager.GetString("View_HelpClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Extract        Alt+1, Alt+2, Alt+3 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpExtract() As String
            Get
                Return ResourceManager.GetString("View_HelpExtract", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 First Artwork        Home 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpFirstArt() As String
            Get
                Return ResourceManager.GetString("View_HelpFirstArt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Toggle Full Screen        F11 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpFullScreen() As String
            Get
                Return ResourceManager.GetString("View_HelpFullScreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Show Information        I 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpInfo() As String
            Get
                Return ResourceManager.GetString("View_HelpInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Last Artwork         End 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpLastArt() As String
            Get
                Return ResourceManager.GetString("View_HelpLastArt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Next Artwork             Ctrl+PageDown, Ctrl+Down Arrow, Ctrl+Right Arrow 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpNextArt() As String
            Get
                Return ResourceManager.GetString("View_HelpNextArt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Next             Right Arrow or Down Arrow, &apos;S&apos;, &apos;D&apos;, &apos;N&apos;, PageDown, &gt;, Space or Enter 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpNextImg() As String
            Get
                Return ResourceManager.GetString("View_HelpNextImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Play        Ctrl+F5 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpPlay() As String
            Get
                Return ResourceManager.GetString("View_HelpPlay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Previous Artwork         Ctrl+PageUp, Ctrl+Up Arrow, Ctrl+Left Arrow 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpPrevArt() As String
            Get
                Return ResourceManager.GetString("View_HelpPrevArt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Previous         Left Arrow or Up Arrow, &apos;W&apos;, &apos;A&apos;, &apos;P&apos;, PageUp, &lt; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpPrevImg() As String
            Get
                Return ResourceManager.GetString("View_HelpPrevImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Show This Help        F1 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpShowHelp() As String
            Get
                Return ResourceManager.GetString("View_HelpShowHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Help Instructions 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpShowInfo() As String
            Get
                Return ResourceManager.GetString("View_HelpShowInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Show File Properties        Alt+Enter 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_HelpShowProp() As String
            Get
                Return ResourceManager.GetString("View_HelpShowProp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Image Viewer 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_ImageBrowser() As String
            Get
                Return ResourceManager.GetString("View_ImageBrowser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Import Time: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Import() As String
            Get
                Return ResourceManager.GetString("View_Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Info... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Info() As String
            Get
                Return ResourceManager.GetString("View_Info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;K-Means Cluster 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_KMeansCluster() As String
            Get
                Return ResourceManager.GetString("View_KMeansCluster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Light Mode 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Light() As String
            Get
                Return ResourceManager.GetString("View_Light", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Loading... 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Loading() As String
            Get
                Return ResourceManager.GetString("View_Loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Median Cut 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_MedianCut() As String
            Get
                Return ResourceManager.GetString("View_MedianCut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Next Image 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_NextImg() As String
            Get
                Return ResourceManager.GetString("View_NextImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 N&amp;ext Artwork 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_NextMs() As String
            Get
                Return ResourceManager.GetString("View_NextMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 File does not exist or path is invalid. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_NoFile() As String
            Get
                Return ResourceManager.GetString("View_NoFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Notes: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Notes() As String
            Get
                Return ResourceManager.GetString("View_Notes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Untitled 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_NoTitle() As String
            Get
                Return ResourceManager.GetString("View_NoTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Octree 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Octree() As String
            Get
                Return ResourceManager.GetString("View_Octree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Open 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Open() As String
            Get
                Return ResourceManager.GetString("View_Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Open &amp;Folder 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_OpenFolder() As String
            Get
                Return ResourceManager.GetString("View_OpenFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &amp;Previous Image 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_PreviousImg() As String
            Get
                Return ResourceManager.GetString("View_PreviousImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 P&amp;revious Artwork 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_PreviousMs() As String
            Get
                Return ResourceManager.GetString("View_PreviousMs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Resolution: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Resolution() As String
            Get
                Return ResourceManager.GetString("View_Resolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Characters: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Roles() As String
            Get
                Return ResourceManager.GetString("View_Roles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Show &amp;Status Bar 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_ShowStatusBar() As String
            Get
                Return ResourceManager.GetString("View_ShowStatusBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Show &amp;Tool Bar 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_ShowToolBar() As String
            Get
                Return ResourceManager.GetString("View_ShowToolBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Follow &amp;System 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_System() As String
            Get
                Return ResourceManager.GetString("View_System", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tags: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Tags() As String
            Get
                Return ResourceManager.GetString("View_Tags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 T&amp;heme 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Theme() As String
            Get
                Return ResourceManager.GetString("View_Theme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Title: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Title() As String
            Get
                Return ResourceManager.GetString("View_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Update Time: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_Update() As String
            Get
                Return ResourceManager.GetString("View_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 UUID: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property View_UUID() As String
            Get
                Return ResourceManager.GetString("View_UUID", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
